const ACTIONS_TYPES = {
  // Movies
  // Get all
  GET_MOVIES_ACTION: 'GET_MOVIES_ACTION',
  GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  // Get by id
  GET_MOVIE_ACTION: 'GET_MOVIE_ACTION',
  GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
  // Create
  POST_MOVIE_ACTION: 'POST_MOVIE_ACTION',
  POST_MOVIE_REQUEST: 'POST_MOVIE_REQUEST',
  POST_MOVIE_SUCCESS: 'POST_MOVIE_SUCCESS',
  POST_MOVIE_ERROR: 'POST_MOVIE_ERROR',
  // Update
  PUT_MOVIE_ACTION: 'PUT_MOVIE_ACTION',
  PUT_MOVIE_REQUEST: 'PUT_MOVIE_REQUEST',
  PUT_MOVIE_SUCCESS: 'PUT_MOVIE_SUCCESS',
  PUT_MOVIE_ERROR: 'PUT_MOVIE_ERROR',
  // Delete
  DELETE_MOVIE_ACTION: 'DELETE_MOVIE_ACTION',
  DELETE_MOVIE_REQUEST: 'DELETE_MOVIE_REQUEST',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
}

export default ACTIONS_TYPES;