const ACTIONS_TYPES = {
  // Movies
  // Get all
  GET_MOVIES_ACTION: 'GET_MOVIES_ACTION',
  GET_MOVIES_REQUEST: 'GET_MOVIES_REQUEST',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  // Get by id
  GET_MOVIE_ACTION: 'GET_MOVIE_ACTION',
  GET_MOVIE_REQUEST: 'GET_MOVIE_REQUEST',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  GET_MOVIE_ERROR: 'GET_MOVIE_ERROR',
  // Create
  POST_MOVIE_ACTION: 'POST_MOVIE_ACTION',
  POST_MOVIE_REQUEST: 'POST_MOVIE_REQUEST',
  POST_MOVIE_SUCCESS: 'POST_MOVIE_SUCCESS',
  POST_MOVIE_ERROR: 'POST_MOVIE_ERROR',
  // Update
  PUT_MOVIE_ACTION: 'PUT_MOVIE_ACTION',
  PUT_MOVIE_REQUEST: 'PUT_MOVIE_REQUEST',
  PUT_MOVIE_SUCCESS: 'PUT_MOVIE_SUCCESS',
  PUT_MOVIE_ERROR: 'PUT_MOVIE_ERROR',
  // Delete
  DELETE_MOVIE_ACTION: 'DELETE_MOVIE_ACTION',
  DELETE_MOVIE_REQUEST: 'DELETE_MOVIE_REQUEST',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
  // Actors
  // Get all
  GET_ACTORS_ACTION: 'GET_ACTORS_ACTION',
  GET_ACTORS_REQUEST: 'GET_ACTORS_REQUEST',
  GET_ACTORS_SUCCESS: 'GET_ACTORS_SUCCESS',
  GET_ACTORS_ERROR: 'GET_ACTORS_ERROR',
  // Get by id
  GET_ACTOR_ACTION: 'GET_ACTOR_ACTION',
  GET_ACTOR_REQUEST: 'GET_ACTOR_REQUEST',
  GET_ACTOR_SUCCESS: 'GET_ACTOR_SUCCESS',
  GET_ACTOR_ERROR: 'GET_ACTOR_ERROR',
  // Create
  POST_ACTOR_ACTION: 'POST_ACTOR_ACTION',
  POST_ACTOR_REQUEST: 'POST_ACTOR_REQUEST',
  POST_ACTOR_SUCCESS: 'POST_ACTOR_SUCCESS',
  POST_ACTOR_ERROR: 'POST_ACTOR_ERROR',
  // Update
  PUT_ACTOR_ACTION: 'PUT_ACTOR_ACTION',
  PUT_ACTOR_REQUEST: 'PUT_ACTOR_REQUEST',
  PUT_ACTOR_SUCCESS: 'PUT_ACTOR_SUCCESS',
  PUT_ACTOR_ERROR: 'PUT_ACTOR_ERROR',
  // Delete
  DELETE_ACTOR_ACTION: 'DELETE_ACTOR_ACTION',
  DELETE_ACTOR_REQUEST: 'DELETE_ACTOR_REQUEST',
  DELETE_ACTOR_SUCCESS: 'DELETE_ACTOR_SUCCESS',
  DELETE_ACTOR_ERROR: 'DELETE_ACTOR_ERROR',
  // Directors
  // Get all directors
  GET_DIRECTORS_ACTION: 'GET_DIRECTORS_ACTION',
  GET_DIRECTORS_REQUEST: 'GET_DIRECTORS_REQUEST',
  GET_DIRECTORS_SUCCESS: 'GET_DIRECTORS_SUCCESS',
  GET_DIRECTORS_ERROR: 'GET_DIRECTORS_ERROR',
  // Create director
  POST_DIRECTOR_ACTION: 'POST_DIRECTOR_ACTION',
  POST_DIRECTOR_REQUEST: 'POST_DIRECTOR_REQUEST',
  POST_DIRECTOR_SUCCESS: 'POST_DIRECTOR_SUCCESS',
  POST_DIRECTOR_ERROR: 'POST_DIRECTOR_ERROR',
  // Uodate director
  PUT_DIRECTOR_ACTION: 'PUT_DIRECTOR_ACTION',
  PUT_DIRECTOR_REQUEST: 'PUT_DIRECTOR_REQUEST',
  PUT_DIRECTOR_SUCCESS: 'PUT_DIRECTOR_SUCCESS',
  PUT_DIRECTOR_ERROR: 'PUT_DIRECTOR_ERROR',
  // Delete director
  DELETE_DIRECTOR_ACTION: 'DELETE_DIRECTOR_ACTION',
  DELETE_DIRECTOR_REQUEST: 'DELETE_DIRECTOR_REQUEST',
  DELETE_DIRECTOR_SUCCESS: 'DELETE_DIRECTOR_SUCCESS',
  DELETE_DIRECTOR_ERROR: 'DELETE_DIRECTOR_ERROR',
}

export default ACTIONS_TYPES;